apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    path: manifests/nginx
    repoURL: https://github.com/MuriloAcsonov/argocd-locally-iac
    targetRevision: main
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    path: manifests/nginx
    repoURL: https://github.com/MuriloAcsonov/argocd-locally-iac
    targetRevision: main
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true