apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://github.com/MuriloAcsonov/argocd-locally-iac/manifests/nginx
    targetRevision: 0.0.1
    helm:
      releaseName: nginx
      parameters:
        - name: service.nodePort
          value: "30080"
        - name: autoscaling.enabled
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://github.com/MuriloAcsonov/argocd-locally-iac/manifests/nginx
    targetRevision: 0.0.1
    helm:
      releaseName: nginx
      parameters:
        - name: service.nodePort
          value: "30081"
        - name: autoscaling.enabled
          value: "false"
  destination:
    server: "https://k3d-dev-server-0:6443"
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true