apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-001
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-001
  template:
    metadata:
      labels:
        app: nginx-001
    spec:
      containers:
        - name: nginx-001
          image: nginx
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-001
  namespace: default
spec:
  selector:
    app: nginx-001
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 80