replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80